development:
  adapter: postgresql
  database: itinefairy_dev
  pool: 50
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: itinefairy_test
  pool: 50
  timeout: 5000
  host: localhost
  port: 5432

staging:
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>

production:
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
